from pythonds3.graphs import Graph

my_graph = Graph()
my_graph.set_vertex('A')
my_graph.set_vertex('B')
my_graph.add_edge('A', 'B')
my_graph.set_vertex('C')
my_graph.add_edge('A', 'C')
my_graph.set_vertex('F')
my_graph.set_vertex('D')
my_graph.add_edge('F', 'D')
my_graph.set_vertex('E')
my_graph.add_edge('D', 'E')
print(my_graph.get_vertex('A'))
print(my_graph.get_vertex('B'))
print(my_graph.get_vertex('C'))
print(my_graph.get_vertex('D'))
print(my_graph.get_vertex('E'))
print(my_graph.get_vertex('F'))